                        <h3>Question:</h3>
                    
                        <div>
                        <table class="gamecreation" align="center">
                          <tbody value='question'>
                           <tr> <td><input type="text" name="question[one][]" ></td> <td><input type="text" name="question[one][]" ></td>  <td><input type="text" name="question[one][]" ></td> <td><input type="text" name="question[one][]" ></td> <td><input type="text" name="question[one][]" ></td>  <td><input type="text" name="question[one][]" ></td> <td><input type="text" name="question[one][]" ></td> <td><input type="text" name="question[one][]" ></td>  <td><input type="text" name="question[one][]" ></td> </tr>
                           <tr> <td><input type="text" name="question[two][]" ></td> <td><input type="text" name="question[two][]" ></td>  <td><input type="text" name="question[two][]" ></td> <td><input type="text" name="question[two][]" ></td> <td><input type="text" name="question[two][]" ></td>  <td><input type="text" name="question[two][]" ></td> <td><input type="text" name="question[two][]" ></td> <td><input type="text" name="question[two][]" ></td>  <td><input type="text" name="question[two][]" ></td> </tr>
                           <tr> <td><input type="text" name="question[three][]" ></td> <td><input type="text" name="question[three][]" ></td>  <td><input type="text" name="question[three][]" ></td> <td><input type="text" name="question[three][]" ></td> <td><input type="text" name="question[three][]" ></td>  <td><input type="text" name="question[three][]" ></td> <td><input type="text" name="question[three][]" ></td> <td><input type="text" name="question[three][]" ></td>  <td><input type="text" name="question[three][]" ></td> </tr>
                           <tr> <td><input type="text" name="question[four][]" ></td> <td><input type="text" name="question[four][]" ></td>  <td><input type="text" name="question[four][]" ></td> <td><input type="text" name="question[four][]" ></td> <td><input type="text" name="question[four][]" ></td>  <td><input type="text" name="question[four][]" ></td> <td><input type="text" name="question[four][]" ></td> <td><input type="text" name="question[four][]" ></td>  <td><input type="text" name="question[four][]" ></td> </tr>
                           <tr> <td><input type="text" name="question[five][]" ></td> <td><input type="text" name="question[five][]" ></td>  <td><input type="text" name="question[five][]" ></td> <td><input type="text" name="question[five][]" ></td> <td><input type="text" name="question[five][]" ></td>  <td><input type="text" name="question[five][]" ></td> <td><input type="text" name="question[five][]" ></td> <td><input type="text" name="question[five][]" ></td>  <td><input type="text" name="question[five][]" ></td> </tr>
                           <tr> <td><input type="text" name="question[six][]" ></td> <td><input type="text" name="question[six][]" ></td>  <td><input type="text" name="question[six][]" ></td> <td><input type="text" name="question[six][]" ></td> <td><input type="text" name="question[six][]" ></td>  <td><input type="text" name="question[six][]" ></td> <td><input type="text" name="question[six][]" ></td> <td><input type="text" name="question[six][]" ></td>  <td><input type="text" name="question[six][]" ></td> </tr>
                           <tr> <td><input type="text" name="question[seven][]" ></td> <td><input type="text" name="question[seven][]" ></td>  <td><input type="text" name="question[seven][]" ></td> <td><input type="text" name="question[seven][]" ></td> <td><input type="text" name="question[seven][]" ></td>  <td><input type="text" name="question[seven][]" ></td> <td><input type="text" name="question[seven][]" ></td> <td><input type="text" name="question[seven][]" ></td>  <td><input type="text" name="question[seven][]" ></td> </tr>
                           <tr> <td><input type="text" name="question[eight][]" ></td> <td><input type="text" name="question[eight][]" ></td>  <td><input type="text" name="question[eight][]" ></td> <td><input type="text" name="question[eight][]" ></td> <td><input type="text" name="question[eight][]" ></td>  <td><input type="text" name="question[eight][]" ></td> <td><input type="text" name="question[eight][]" ></td> <td><input type="text" name="question[eight][]" ></td>  <td><input type="text" name="question[eight][]" ></td> </tr>
                           <tr> <td><input type="text" name="question[nine][]" ></td> <td><input type="text" name="question[nine][]" ></td>  <td><input type="text" name="question[nine][]" ></td> <td><input type="text" name="question[nine][]" ></td> <td><input type="text" name="question[nine][]" ></td>  <td><input type="text" name="question[nine][]" ></td> <td><input type="text" name="question[nine][]" ></td> <td><input type="text" name="question[nine][]" ></td>  <td><input type="text" name="question[nine][]" ></td> </tr>
                           
                           </tbody>
                        </table>

                        </div>


                        <br/>
                        <h3>Answer:</h3>
                        <div>
                        <table class="gamecreation" align="center">
                          <tbody  value='answer'>
                           <tr> <td><input type="text" name="answer[one][]" ></td> <td><input type="text" name="answer[one][]" ></td>  <td><input type="text" name="answer[one][]" ></td> <td><input type="text" name="answer[one][]" ></td> <td><input type="text" name="answer[one][]" ></td>  <td><input type="text" name="answer[one][]" ></td> <td><input type="text" name="answer[one][]" ></td> <td><input type="text" name="answer[one][]" ></td>  <td><input type="text" name="answer[one][]" ></td> </tr>
                           <tr> <td><input type="text" name="answer[two][]" ></td> <td><input type="text" name="answer[two][]" ></td>  <td><input type="text" name="answer[two][]" ></td> <td><input type="text" name="answer[two][]" ></td> <td><input type="text" name="answer[two][]" ></td>  <td><input type="text" name="answer[two][]" ></td> <td><input type="text" name="answer[two][]" ></td> <td><input type="text" name="answer[two][]" ></td>  <td><input type="text" name="answer[two][]" ></td> </tr>
                           <tr> <td><input type="text" name="answer[three][]" ></td> <td><input type="text" name="answer[three][]" ></td>  <td><input type="text" name="answer[three][]" ></td> <td><input type="text" name="answer[three][]" ></td> <td><input type="text" name="answer[three][]" ></td>  <td><input type="text" name="answer[three][]" ></td> <td><input type="text" name="answer[three][]" ></td> <td><input type="text" name="answer[three][]" ></td>  <td><input type="text" name="answer[three][]" ></td> </tr>
                           <tr> <td><input type="text" name="answer[four][]" ></td> <td><input type="text" name="answer[four][]" ></td>  <td><input type="text" name="answer[four][]" ></td> <td><input type="text" name="answer[four][]" ></td> <td><input type="text" name="answer[four][]" ></td>  <td><input type="text" name="answer[four][]" ></td> <td><input type="text" name="answer[four][]" ></td> <td><input type="text" name="answer[four][]" ></td>  <td><input type="text" name="answer[four][]" ></td> </tr>
                           <tr> <td><input type="text" name="answer[five][]" ></td> <td><input type="text" name="answer[five][]" ></td>  <td><input type="text" name="answer[five][]" ></td> <td><input type="text" name="answer[five][]" ></td> <td><input type="text" name="answer[five][]" ></td>  <td><input type="text" name="answer[five][]" ></td> <td><input type="text" name="answer[five][]" ></td> <td><input type="text" name="answer[five][]" ></td>  <td><input type="text" name="answer[five][]" ></td> </tr>
                           <tr> <td><input type="text" name="answer[six][]" ></td> <td><input type="text" name="answer[six][]" ></td>  <td><input type="text" name="answer[six][]" ></td> <td><input type="text" name="answer[six][]" ></td> <td><input type="text" name="answer[six][]" ></td>  <td><input type="text" name="answer[six][]" ></td> <td><input type="text" name="answer[six][]" ></td> <td><input type="text" name="answer[six][]" ></td>  <td><input type="text" name="answer[six][]" ></td> </tr>
                           <tr> <td><input type="text" name="answer[seven][]" ></td> <td><input type="text" name="answer[seven][]" ></td>  <td><input type="text" name="answer[seven][]" ></td> <td><input type="text" name="answer[seven][]" ></td> <td><input type="text" name="answer[seven][]" ></td>  <td><input type="text" name="answer[seven][]" ></td> <td><input type="text" name="answer[seven][]" ></td> <td><input type="text" name="answer[seven][]" ></td>  <td><input type="text" name="answer[seven][]" ></td> </tr>
                           <tr> <td><input type="text" name="answer[eight][]" ></td> <td><input type="text" name="answer[eight][]" ></td>  <td><input type="text" name="answer[eight][]" ></td> <td><input type="text" name="answer[eight][]" ></td> <td><input type="text" name="answer[eight][]" ></td>  <td><input type="text" name="answer[eight][]" ></td> <td><input type="text" name="answer[eight][]" ></td> <td><input type="text" name="answer[eight][]" ></td>  <td><input type="text" name="answer[eight][]" ></td> </tr>
                           <tr> <td><input type="text" name="answer[nine][]" ></td> <td><input type="text" name="answer[nine][]" ></td>  <td><input type="text" name="answer[nine][]" ></td> <td><input type="text" name="answer[nine][]" ></td> <td><input type="text" name="answer[nine][]" ></td>  <td><input type="text" name="answer[nine][]" ></td> <td><input type="text" name="answer[nine][]" ></td> <td><input type="text" name="answer[nine][]" ></td>  <td><input type="text" name="answer[nine][]" ></td> </tr>
                           

                           </tbody>
                        </table>

                        </div>